# 03-01 Linear Regression and Autograd
## 1. Data Definition
## 2. Hypothesis 수립
## 3. Compute loss
    - cons function = loss function = error function = object function
## 4. Gradient Descent

In [1]:
# pytorch로 선형 회귀 구현
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [2]:
#변수 선언
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [3]:
# weight, bias 초기화
W = torch.zeros(1, requires_grad=True) # requires_grad=True 학습을 통해 계속 값이 변경되는 변수임
print(W)
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [4]:
# hypothesis 수립
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [5]:
# cost function 선언
cost = torch.mean((hypothesis - y_train) ** 2) # MSE
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [6]:
# Gradient Descent 구현
optimizer = optim.SGD([W,b], lr=0.01) # 학습대상 가중치를 입력

#gradient 0으로 초기화
optimizer.zero_grad()
# 비용함수 미분하여 gradient 계산
cost.backward()
# W와 b를 업데이트
optimizer.step()

In [7]:
nb_epochs = 1999
for epoch in range(nb_epochs +1):
    # H(x) 계산
    hypothesis = x_train * W + b
    # cost 계산
    cost = torch.mean((hypothesis-y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad() # 미분값 초기화 안하면 계속 누적됨
    cost.backward()
    optimizer.step()

    # 100번 마다 로그 출력
    if epoch % 100 == 0:
        print(f'Epoch {epoch:4d}/{nb_epochs} W: {W.item():.3f}, b: {b.item():.3f} Cost: {cost.item():.6f}')

Epoch    0/1999 W: 0.353, b: 0.151 Cost: 14.770963
Epoch  100/1999 W: 1.746, b: 0.577 Cost: 0.047939
Epoch  200/1999 W: 1.801, b: 0.453 Cost: 0.029624
Epoch  300/1999 W: 1.843, b: 0.356 Cost: 0.018306
Epoch  400/1999 W: 1.877, b: 0.280 Cost: 0.011312
Epoch  500/1999 W: 1.903, b: 0.220 Cost: 0.006990
Epoch  600/1999 W: 1.924, b: 0.173 Cost: 0.004319
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002669
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001649
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001019
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000630
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000389
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000240
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

In [8]:
# Autograd
w = torch.tensor(2.0, requires_grad=True)
y = w**2
z = 2*y + 5
z.backward()
print(f'수식을 w로 미분한 값 : {w.grad}') # dz/dw = dz/dy * dy/dw = 2 * 2w = 4w

수식을 w로 미분한 값 : 8.0


In [9]:
## Multivariable Linear regression
# 훈련 데이터
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 가중치 w와 편향 b 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


In [10]:
# 행렬로 구현
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [11]:
# 가중치와 편향 선언
W = torch.zeros((3, 1), requires_grad=True) # 3x1
b = torch.zeros(1, requires_grad=True)

hypothesis = x_train.matmul(W) + b # 행렬곱으로 표현

optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

In [12]:
# 임의의 입력 값에 대한 예측
with torch.no_grad(): # 이 블록에서는 역전파 계싼 비활성화 -> 예측하는데 가중치 업데이트 필요 없음
    new_input = torch.FloatTensor([[75,85,72]]) # 예측하고 싶은 임의의 입력
    prediction = new_input.matmul(W) + b
    print(f'Predicted value for input {new_input.squeeze().tolist()}: {prediction.item()}') # 입력값 리스트로 변환해 보기 편하게

Predicted value for input [75.0, 85.0, 72.0]: 156.8051300048828


In [1]:
# 03-03 nn.Module과 클래스로 구현
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [5]:
# 데이터 y = 2x
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 모델 선언 및 초기화, 단순 선형 회귀 -> input_dim=1, output_dim=1

model = nn.Linear(1,1)
print(list(model.parameters())) # 첫번째 값 W , 두번째 값 b 랜덤 초기화 상태
    

[Parameter containing:
tensor([[-0.9414]], requires_grad=True), Parameter containing:
tensor([0.5997], requires_grad=True)]


In [6]:
# optimizer 설정 , 경사하강법 SGD 사용, lr = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# 전체 훈련 데이터에 대해 경사 하강법을 2000번 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # 파이토치에서 제공하는 MSE

    # cost로 H(x) 개선
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0 :
        # 100번 마다 로그 출력
        print(f'Epoch : {epoch:4d}/{nb_epochs} Cost : {cost.item():.6f}')

Epoch :    0/2000 Cost : 33.679783
Epoch :  100/2000 Cost : 0.223159
Epoch :  200/2000 Cost : 0.137899
Epoch :  300/2000 Cost : 0.085213
Epoch :  400/2000 Cost : 0.052656
Epoch :  500/2000 Cost : 0.032539
Epoch :  600/2000 Cost : 0.020107
Epoch :  700/2000 Cost : 0.012425
Epoch :  800/2000 Cost : 0.007678
Epoch :  900/2000 Cost : 0.004744
Epoch : 1000/2000 Cost : 0.002932
Epoch : 1100/2000 Cost : 0.001812
Epoch : 1200/2000 Cost : 0.001119
Epoch : 1300/2000 Cost : 0.000692
Epoch : 1400/2000 Cost : 0.000427
Epoch : 1500/2000 Cost : 0.000264
Epoch : 1600/2000 Cost : 0.000163
Epoch : 1700/2000 Cost : 0.000101
Epoch : 1800/2000 Cost : 0.000062
Epoch : 1900/2000 Cost : 0.000039
Epoch : 2000/2000 Cost : 0.000024


In [7]:
# 임의의 입력 4를 선언
new_var = torch.FloatTensor([[4.0]])
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산
# y=2x 이므로 입력이 4면 8에 가까운 값이 나와야 학습 잘 된것
print("훈련 후 입력이 4일 때의 예측값 : ", pred_y)

훈련 후 입력이 4일 때의 예측값 :  tensor([[7.9902]], grad_fn=<AddmmBackward0>)


In [8]:
print(list(model.parameters())) # 학습후 W,b 값

[Parameter containing:
tensor([[1.9943]], requires_grad=True), Parameter containing:
tensor([0.0128], requires_grad=True)]


In [18]:
# 다중 선형 회귀 구현

# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [19]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1
model = nn.Linear(3,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.1601, 0.0285, 0.2109]], requires_grad=True), Parameter containing:
tensor([-0.2250], requires_grad=True)]


In [20]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

# 전체 훈련 데이터에 대해 경사 하강법을 2000번 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # 파이토치에서 제공하는 MSE

    # cost로 H(x) 개선
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0 :
        # 100번 마다 로그 출력
        print(f'Epoch : {epoch:4d}/{nb_epochs} Cost : {cost.item():.6f}')

Epoch :    0/2000 Cost : 19085.046875
Epoch :  100/2000 Cost : 0.954051
Epoch :  200/2000 Cost : 0.925118
Epoch :  300/2000 Cost : 0.897646
Epoch :  400/2000 Cost : 0.871580
Epoch :  500/2000 Cost : 0.846827
Epoch :  600/2000 Cost : 0.823312
Epoch :  700/2000 Cost : 0.800989
Epoch :  800/2000 Cost : 0.779788
Epoch :  900/2000 Cost : 0.759638
Epoch : 1000/2000 Cost : 0.740494
Epoch : 1100/2000 Cost : 0.722297
Epoch : 1200/2000 Cost : 0.705017
Epoch : 1300/2000 Cost : 0.688583
Epoch : 1400/2000 Cost : 0.672957
Epoch : 1500/2000 Cost : 0.658109
Epoch : 1600/2000 Cost : 0.643980
Epoch : 1700/2000 Cost : 0.630553
Epoch : 1800/2000 Cost : 0.617762
Epoch : 1900/2000 Cost : 0.605604
Epoch : 2000/2000 Cost : 0.594023


In [21]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.7086]], grad_fn=<AddmmBackward0>)


In [22]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.7596, 0.5041, 0.7486]], requires_grad=True), Parameter containing:
tensor([-0.2157], requires_grad=True)]


In [23]:
# 모델을 클래스로 구현하기

class LinearRegressionModel(nn.Module): # torch.nn.Module을 상속받는 파이썬 클래스
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1)

    def forward(self, x):
        return self.linear(x)

In [24]:
model = LinearRegressionModel()

In [25]:
# 다중 선형회귀 클래스로 구현
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)

    def forward(self, x):
        return self.linear(x)

model = MultivariateLinearRegressionModel()

In [26]:
# 03-04 Mini Batch and DataLoader
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader



x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  90],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [27]:
dataset = TensorDataset(x_train, y_train)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [28]:
	

nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader): # 미니 배치 별로 계산
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 46380.019531
Epoch    0/20 Batch 2/3 Cost: 20313.339844
Epoch    0/20 Batch 3/3 Cost: 6635.396973
Epoch    1/20 Batch 1/3 Cost: 1607.853516
Epoch    1/20 Batch 2/3 Cost: 330.187775
Epoch    1/20 Batch 3/3 Cost: 85.304123
Epoch    2/20 Batch 1/3 Cost: 50.594917
Epoch    2/20 Batch 2/3 Cost: 9.879074
Epoch    2/20 Batch 3/3 Cost: 11.024374
Epoch    3/20 Batch 1/3 Cost: 0.413609
Epoch    3/20 Batch 2/3 Cost: 3.910518
Epoch    3/20 Batch 3/3 Cost: 0.422770
Epoch    4/20 Batch 1/3 Cost: 0.359748
Epoch    4/20 Batch 2/3 Cost: 2.718346
Epoch    4/20 Batch 3/3 Cost: 0.771725
Epoch    5/20 Batch 1/3 Cost: 0.125672
Epoch    5/20 Batch 2/3 Cost: 1.914474
Epoch    5/20 Batch 3/3 Cost: 1.032455
Epoch    6/20 Batch 1/3 Cost: 1.331316
Epoch    6/20 Batch 2/3 Cost: 1.266491
Epoch    6/20 Batch 3/3 Cost: 0.000096
Epoch    7/20 Batch 1/3 Cost: 1.861683
Epoch    7/20 Batch 2/3 Cost: 0.572785
Epoch    7/20 Batch 3/3 Cost: 0.000053
Epoch    8/20 Batch 1/3 Cost: 0.724831
Epoch 

In [29]:

# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.8289]], grad_fn=<AddmmBackward0>)


In [31]:
# Custom Dataset 으로 선형회귀 구현
# Dataset 상속
from torch.utils.data import Dataset
class CustomDataset(Dataset):
    def __init__(self):
        self.x_data = [[73, 80, 75],
                       [93, 88, 93],
                       [89, 91, 90],
                       [96, 98, 100],
                       [73, 66, 70]]
        self.y_data = [[152], [185], [180], [196], [142]]

    def __len__(self):
        return len(self.x_data)

    def __getitem__(self, idx):
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        return x, y

In [32]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader): # 미니 배치 별로 계산
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 11408.118164
Epoch    0/20 Batch 2/3 Cost: 4223.604980
Epoch    0/20 Batch 3/3 Cost: 1974.814819
Epoch    1/20 Batch 1/3 Cost: 324.249054
Epoch    1/20 Batch 2/3 Cost: 73.079018
Epoch    1/20 Batch 3/3 Cost: 21.028164
Epoch    2/20 Batch 1/3 Cost: 9.086073
Epoch    2/20 Batch 2/3 Cost: 3.780728
Epoch    2/20 Batch 3/3 Cost: 0.581914
Epoch    3/20 Batch 1/3 Cost: 0.124037
Epoch    3/20 Batch 2/3 Cost: 0.772523
Epoch    3/20 Batch 3/3 Cost: 1.031804
Epoch    4/20 Batch 1/3 Cost: 0.321776
Epoch    4/20 Batch 2/3 Cost: 0.535748
Epoch    4/20 Batch 3/3 Cost: 0.742123
Epoch    5/20 Batch 1/3 Cost: 0.950820
Epoch    5/20 Batch 2/3 Cost: 0.509644
Epoch    5/20 Batch 3/3 Cost: 0.511853
Epoch    6/20 Batch 1/3 Cost: 0.583526
Epoch    6/20 Batch 2/3 Cost: 0.568336
Epoch    6/20 Batch 3/3 Cost: 1.151587
Epoch    7/20 Batch 1/3 Cost: 0.556057
Epoch    7/20 Batch 2/3 Cost: 0.154402
Epoch    7/20 Batch 3/3 Cost: 0.981622
Epoch    8/20 Batch 1/3 Cost: 0.547159
Epoch    8/

In [ ]:
# 03-05 벡터와 행렬 연산 복습하기